"""empty message

Revision ID: 834fa1ba1ee6
Revises: dce4ae7d29af
Create Date: 2025-12-06 01:54:25.502848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '834fa1ba1ee6'
down_revision = 'dce4ae7d29af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('starships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorites_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('cargo_capacity', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('passengers', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('crew', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('model', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('cost_in_credits', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('starshiip_class', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('hyperdrive_rating', sa.String(length=80), nullable=False))
        batch_op.drop_constraint('starships_email_key', type_='unique')
        batch_op.create_foreign_key(None, 'favorites', ['favorites_id'], ['id'])
        batch_op.drop_column('is_active')
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('starships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('starships_email_key', ['email'])
        batch_op.drop_column('hyperdrive_rating')
        batch_op.drop_column('starshiip_class')
        batch_op.drop_column('cost_in_credits')
        batch_op.drop_column('model')
        batch_op.drop_column('crew')
        batch_op.drop_column('passengers')
        batch_op.drop_column('cargo_capacity')
        batch_op.drop_column('name')
        batch_op.drop_column('favorites_id')

    # ### end Alembic commands ###
