"""empty message

Revision ID: dce4ae7d29af
Revises: 9eb33b2f4897
Create Date: 2025-12-06 01:45:42.715298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dce4ae7d29af'
down_revision = '9eb33b2f4897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorites_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('classification', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('designation', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('eye_colors', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('hair_colors', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('skin_colors', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('language', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('average_lifespan', sa.String(length=80), nullable=False))
        batch_op.drop_constraint('species_email_key', type_='unique')
        batch_op.create_foreign_key(None, 'favorites', ['favorites_id'], ['id'])
        batch_op.drop_column('is_active')
        batch_op.drop_column('email')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('species_email_key', ['email'])
        batch_op.drop_column('average_lifespan')
        batch_op.drop_column('language')
        batch_op.drop_column('skin_colors')
        batch_op.drop_column('hair_colors')
        batch_op.drop_column('eye_colors')
        batch_op.drop_column('designation')
        batch_op.drop_column('classification')
        batch_op.drop_column('name')
        batch_op.drop_column('favorites_id')

    # ### end Alembic commands ###
